### ISSUE TITLE
Is there any benchmark that compares Sequoia against vanilla speculative decoding?

### ISSUE THREAD

**Issue by KexinFeng** [Infini-AI-Lab/Sequoia#10]
Hi,

Thanks for the great work! 

I'm wondering if there is any benchmark that compares Sequoia against vanilla speculative decoding?

**Comment by preminstrel** [comment]
Once you get your acceptance rate, I think you can directly calculate the theoretical best gamma and speedup for vanilla speculative decoding.

**Comment by dreaming-panda** [comment]
Hello, you can use 4-chain, 8-chain in L40_growmaps as growmaps, which will produce "tree structures" for vanilla speculative decoding. Thank you!
